Switch to Debian stretch
camptocamp/docker-python-gis pull request #2
Opened 2017-11-02 14:48 UTC by gberaudo

Stretch is the new stable version of Debian.
Additionnally, this version fixes the issue with RFC 3484 rule 9 and DNS roundrobin.

2017-11-02 15:18 UTC, pvalsecc commented
This is too dangerous. We'll break backward compatibility and most of the images using c2cwsgiutils won't build anymore.

2017-11-02 15:33 UTC, pvalsecc requested changes
Should not be done without introduction a new docker tag

2017-11-03 09:35 UTC, gberaudo commented
I created the new branch and configured travis for daily builds.
In addition I disabled the daily build for master.

2017-11-03 09:38 UTC, gberaudo commented
The tag is created so I am now closing this PR.

2017-11-03 09:38 UTC, closed without merging